export const fixtureManifest = [
  {
    name: 'rightmove fixture uses PAGE_MODEL parser',
    file: 'rightmove.html',
    url: 'https://www.rightmove.co.uk/properties/123456789',
    expected: {
      parser: 'rightmove',
      title: 'Station Quarter Flat',
      price: 235000,
      bedrooms: 2,
      bathrooms: 1,
      location: 'Birmingham City Centre',
      features: ['parking', 'balcony'],
      fieldSources: {
        title: 'site_specific',
        price: 'site_specific',
        bedrooms: 'site_specific',
        bathrooms: 'site_specific',
        location: 'site_specific',
      },
    },
  },
  {
    name: 'zoopla fixture uses __NEXT_DATA__ parser',
    file: 'zoopla.html',
    url: 'https://www.zoopla.co.uk/for-sale/details/42/',
    expected: {
      parser: 'zoopla',
      title: 'Canal Side Apartment',
      price: 245000,
      bedrooms: 2,
      bathrooms: 2,
      location: 'Birmingham',
      features: ['garden', 'lift'],
      fieldSources: {
        title: 'site_specific',
        price: 'site_specific',
        bedrooms: 'site_specific',
        bathrooms: 'site_specific',
        location: 'site_specific',
      },
    },
  },
  {
    name: 'onthemarket fixture uses __NEXT_DATA__ parser with json-ld present',
    file: 'onthemarket.html',
    url: 'https://www.onthemarket.com/details/7/',
    expected: {
      parser: 'onthemarket',
      title: 'Garden View Flat',
      price: 240000,
      bedrooms: 2,
      bathrooms: 1,
      location: 'Edgbaston, Birmingham',
      features: ['parking', 'garden'],
      hadJsonLd: true,
      fieldSources: {
        title: 'site_specific',
        price: 'site_specific',
        bedrooms: 'site_specific',
        bathrooms: 'site_specific',
        location: 'site_specific',
      },
    },
  },
];
