export const fixtureManifest = [
  {
    name: 'rightmove fixture uses PAGE_MODEL parser',
    file: 'rightmove.html',
    url: 'https://www.rightmove.co.uk/properties/123456789',
    expected: {
      parser: 'rightmove',
      title: 'Station Quarter Flat',
      price: 235000,
      bedrooms: 2,
      bathrooms: 1,
      location: 'Birmingham City Centre',
      features: ['parking', 'balcony'],
      fieldSources: {
        title: 'site_specific',
        price: 'site_specific',
        bedrooms: 'site_specific',
        bathrooms: 'site_specific',
        location: 'site_specific',
      },
    },
  },
  {
    name: 'zoopla fixture uses __NEXT_DATA__ parser',
    file: 'zoopla.html',
    url: 'https://www.zoopla.co.uk/for-sale/details/42/',
    expected: {
      parser: 'zoopla',
      title: 'Canal Side Apartment',
      price: 245000,
      bedrooms: 2,
      bathrooms: 2,
      location: 'Birmingham',
      features: ['garden', 'lift'],
      fieldSources: {
        title: 'site_specific',
        price: 'site_specific',
        bedrooms: 'site_specific',
        bathrooms: 'site_specific',
        location: 'site_specific',
      },
    },
  },
  {
    name: 'onthemarket fixture uses __NEXT_DATA__ parser with json-ld present',
    file: 'onthemarket.html',
    url: 'https://www.onthemarket.com/details/7/',
    expected: {
      parser: 'onthemarket',
      title: 'Garden View Flat',
      price: 240000,
      bedrooms: 2,
      bathrooms: 1,
      location: 'Edgbaston, Birmingham',
      features: ['parking', 'garden'],
      hadJsonLd: true,
      fieldSources: {
        title: 'site_specific',
        price: 'site_specific',
        bedrooms: 'site_specific',
        bathrooms: 'site_specific',
        location: 'site_specific',
      },
    },
  },
  {
    name: 'rightmove minimal fixture tolerates missing bathrooms',
    file: 'rightmove_minimal.html',
    url: 'https://www.rightmove.co.uk/properties/555555555',
    expected: {
      parser: 'rightmove',
      title: 'Compact City Flat',
      price: 199950,
      bedrooms: 1,
      bathrooms: 0,
      location: 'Jewellery Quarter, Birmingham',
      features: [],
      fieldSources: {
        title: 'site_specific',
        price: 'site_specific',
        bedrooms: 'site_specific',
        location: 'site_specific',
      },
    },
  },
  {
    name: 'zoopla fixture falls back cleanly when baths are absent',
    file: 'zoopla_no_baths.html',
    url: 'https://www.zoopla.co.uk/for-sale/details/77/',
    expected: {
      parser: 'zoopla',
      title: 'Warehouse Loft',
      price: 230000,
      bedrooms: 2,
      bathrooms: 0,
      location: 'Digbeth, Birmingham',
      features: ['walkable'],
      fieldSources: {
        title: 'site_specific',
        price: 'site_specific',
        bedrooms: 'site_specific',
        location: 'site_specific',
      },
    },
  },
  {
    name: 'onthemarket text fallback still extracts core fields',
    file: 'onthemarket_text_fallback.html',
    url: 'https://www.onthemarket.com/details/88/',
    expected: {
      parser: 'onthemarket',
      title: 'Quiet Road Apartment',
      price: 210000,
      bedrooms: 2,
      bathrooms: 1,
      location: 'Harborne, Birmingham',
      features: ['quiet street', 'lift'],
      fieldSources: {
        title: 'site_specific',
        price: 'site_specific',
        bedrooms: 'site_specific',
        bathrooms: 'site_specific',
        location: 'text_or_meta',
      },
    },
  },
];
