export const fixtureManifest = [
  {
    name: 'rightmove fixture uses PAGE_MODEL parser',
    variant: 'standard',
    sourceType: 'synthetic',
    notes: 'Baseline Rightmove PAGE_MODEL extraction.',
    file: 'rightmove.html',
    url: 'https://www.rightmove.co.uk/properties/123456789',
    expected: {
      parser: 'rightmove',
      title: 'Station Quarter Flat',
      price: 235000,
      bedrooms: 2,
      bathrooms: 1,
      location: 'Birmingham City Centre',
      features: ['parking', 'balcony'],
      fieldSources: {
        title: 'site_specific',
        price: 'site_specific',
        bedrooms: 'site_specific',
        bathrooms: 'site_specific',
        location: 'site_specific',
      },
    },
  },
  {
    name: 'zoopla fixture uses __NEXT_DATA__ parser',
    variant: 'standard',
    sourceType: 'synthetic',
    notes: 'Baseline Zoopla Next.js extraction.',
    file: 'zoopla.html',
    url: 'https://www.zoopla.co.uk/for-sale/details/42/',
    expected: {
      parser: 'zoopla',
      title: 'Canal Side Apartment',
      price: 245000,
      bedrooms: 2,
      bathrooms: 2,
      location: 'Birmingham',
      features: ['garden', 'lift'],
      fieldSources: {
        title: 'site_specific',
        price: 'site_specific',
        bedrooms: 'site_specific',
        bathrooms: 'site_specific',
        location: 'site_specific',
      },
    },
  },
  {
    name: 'onthemarket fixture uses __NEXT_DATA__ parser with json-ld present',
    variant: 'standard',
    sourceType: 'synthetic',
    notes: 'Structured portal data plus JSON-LD present.',
    file: 'onthemarket.html',
    url: 'https://www.onthemarket.com/details/7/',
    expected: {
      parser: 'onthemarket',
      title: 'Garden View Flat',
      price: 240000,
      bedrooms: 2,
      bathrooms: 1,
      location: 'Edgbaston, Birmingham',
      features: ['parking', 'garden'],
      hadJsonLd: true,
      fieldSources: {
        title: 'site_specific',
        price: 'site_specific',
        bedrooms: 'site_specific',
        bathrooms: 'site_specific',
        location: 'site_specific',
      },
    },
  },
  {
    name: 'rightmove minimal fixture tolerates missing bathrooms',
    variant: 'minimal',
    sourceType: 'synthetic',
    notes: 'Tests missing bathroom handling.',
    file: 'rightmove_minimal.html',
    url: 'https://www.rightmove.co.uk/properties/555555555',
    expected: {
      parser: 'rightmove',
      title: 'Compact City Flat',
      price: 199950,
      bedrooms: 1,
      bathrooms: 0,
      location: 'Jewellery Quarter, Birmingham',
      features: [],
      fieldSources: {
        title: 'site_specific',
        price: 'site_specific',
        bedrooms: 'site_specific',
        location: 'site_specific',
      },
    },
  },
  {
    name: 'zoopla fixture falls back cleanly when baths are absent',
    variant: 'missing-baths',
    sourceType: 'synthetic',
    notes: 'Tests missing bath count and walkable feature synonym.',
    file: 'zoopla_no_baths.html',
    url: 'https://www.zoopla.co.uk/for-sale/details/77/',
    expected: {
      parser: 'zoopla',
      title: 'Warehouse Loft',
      price: 230000,
      bedrooms: 2,
      bathrooms: 0,
      location: 'Digbeth, Birmingham',
      features: ['walkable'],
      fieldSources: {
        title: 'site_specific',
        price: 'site_specific',
        bedrooms: 'site_specific',
        location: 'site_specific',
      },
    },
  },
  {
    name: 'onthemarket text fallback still extracts core fields',
    variant: 'text-fallback',
    sourceType: 'synthetic',
    notes: 'Tests mostly text/meta fallback with portal-specific title aid.',
    file: 'onthemarket_text_fallback.html',
    url: 'https://www.onthemarket.com/details/88/',
    expected: {
      parser: 'onthemarket',
      title: 'Quiet Road Apartment',
      price: 210000,
      bedrooms: 2,
      bathrooms: 1,
      location: 'Harborne, Birmingham',
      features: ['quiet street', 'lift'],
      fieldSources: {
        title: 'site_specific',
        price: 'site_specific',
        bedrooms: 'site_specific',
        bathrooms: 'site_specific',
        location: 'text_regex',
      },
    },
  },
  {
    name: 'generic host falls back to json-ld and text signals',
    variant: 'generic-jsonld',
    sourceType: 'synthetic',
    notes: 'Exercises the generic parser path on a non-portal host.',
    file: 'generic_jsonld_fallback.html',
    url: 'https://example-homes.test/listings/leafy-court',
    expected: {
      parser: 'generic',
      title: 'Leafy Court Apartment',
      price: 215000,
      bedrooms: 2,
      bathrooms: 1,
      location: 'Moseley, Birmingham',
      features: ['parking', 'balcony', 'lift'],
      hadJsonLd: true,
      fieldSources: {
        title: 'json_ld',
        price: 'json_ld',
        bedrooms: 'json_ld',
        bathrooms: 'text_regex',
        location: 'json_ld'
      },
    },
  },
  {
    name: 'generic host supports flexible assertions for fallback extraction',
    variant: 'generic-flex',
    sourceType: 'synthetic',
    notes: 'Demonstrates flexible assertion fields for future imperfect real-world fixtures.',
    file: 'generic_jsonld_fallback.html',
    url: 'https://example-homes.test/listings/leafy-court',
    expected: {
      allowedParsers: ['generic'],
      titleIncludes: 'Leafy Court',
      minPrice: 200000,
      bedrooms: 2,
      bathrooms: 1,
      locationIncludes: 'Birmingham',
      featuresAnyOf: [['parking', 'garage'], ['balcony', 'garden']],
      fieldSources: {
        title: 'json_ld',
        location: 'json_ld'
      },
    },
  },
];
